"""add rating to generated content

Revision ID: 5de72184efab
Revises: eac5326a035b
Create Date: 2026-07-05 22:53:58.196995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de72184efab'
down_revision: Union[str, Sequence[str], None] = 'eac5326a035b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_contents', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_contents', 'rating')
    # ### end Alembic commands ###
