"""create content generation tables

Revision ID: eac5326a035b
Revises: 20260705_0001
Create Date: 2026-07-05 22:50:06.864430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac5326a035b'
down_revision: Union[str, Sequence[str], None] = '20260705_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('audience', sa.String(length=200), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_generations_content_type'), 'content_generations', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_generations_job_id'), 'content_generations', ['job_id'], unique=True)
    op.create_index(op.f('ix_content_generations_status'), 'content_generations', ['status'], unique=False)
    op.create_index(op.f('ix_content_generations_user_id'), 'content_generations', ['user_id'], unique=False)
    op.create_table('generated_contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('active_writer', sa.String(length=100), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_contents_content_type'), 'generated_contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_generated_contents_generation_id'), 'generated_contents', ['generation_id'], unique=True)
    op.create_index(op.f('ix_generated_contents_user_id'), 'generated_contents', ['user_id'], unique=False)
    op.create_table('generation_debug_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('generation_id', sa.String(length=36), nullable=False),
    sa.Column('outline_payload', sa.JSON(), nullable=True),
    sa.Column('search_payload', sa.JSON(), nullable=True),
    sa.Column('draft_payload', sa.JSON(), nullable=True),
    sa.Column('critique_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['content_generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_debug_data_generation_id'), 'generation_debug_data', ['generation_id'], unique=True)
    op.create_index(op.f('ix_generation_debug_data_user_id'), 'generation_debug_data', ['user_id'], unique=False)
    op.add_column('generation_jobs', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_generation_jobs_user_id'), 'generation_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_jobs_user_id'), table_name='generation_jobs')
    op.drop_column('generation_jobs', 'user_id')
    op.drop_index(op.f('ix_generation_debug_data_user_id'), table_name='generation_debug_data')
    op.drop_index(op.f('ix_generation_debug_data_generation_id'), table_name='generation_debug_data')
    op.drop_table('generation_debug_data')
    op.drop_index(op.f('ix_generated_contents_user_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_generation_id'), table_name='generated_contents')
    op.drop_index(op.f('ix_generated_contents_content_type'), table_name='generated_contents')
    op.drop_table('generated_contents')
    op.drop_index(op.f('ix_content_generations_user_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_status'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_job_id'), table_name='content_generations')
    op.drop_index(op.f('ix_content_generations_content_type'), table_name='content_generations')
    op.drop_table('content_generations')
    # ### end Alembic commands ###
